export const FIELD_TYPES = {
  FULL_NAME: 'full_name',
  FIRST_NAME: 'first_name',
  LAST_NAME: 'last_name',
  EMAIL: 'email',
  PHONE_NUMBER: 'phone_number',
  AGE: 'age',
  TITLE: 'title',
  DESCRIPTION: 'description',
  COUNTRY: 'country',
  STATE: 'state',
  CITY: 'city',
  GENDER: 'gender',
  CATEGORY: 'category',
  OPTIONS: 'options',
  PREFERENCES: 'preferences',
  INTERESTS: 'interests',
  DATE_OF_BIRTH: 'date_of_birth',
  START_DATE: 'start_date',
  END_DATE: 'end_date',
  APPOINTMENT_DATE: 'appointment_date',
  APPOINTMENT_TIME: 'appointment_time',
  CREATED_AT: 'created_at',
  FILE_UPLOAD: 'file_upload',
  DOCUMENT: 'document',
  PROFILE_IMAGE: 'profile_image',
  ATTACHMENTS: 'attachments',
  PASSWORD: 'password',
  CONFIRM_PASSWORD: 'confirm_password',
  // OTP_CODE: 'otp_code',
  // VERIFICATION_CODE: 'verification_code',
  ADDITIONAL_INFO: 'additional_info',
  CUSTOM_FIELD_1: 'custom_field_1',
  CUSTOM_FIELD_2: 'custom_field_2',
  REPEATABLE_GROUP: 'repeatable_group',
  CONDITIONAL_FIELD: 'conditional_field',
  LOCATION: 'location',
  ADDRESS: 'address',
  LATITUDE: 'latitude',
  LONGITUDE: 'longitude',
  WEBSITE_URL: 'website_url',
  SIGNATURE: 'signature',
  RICH_TEXT_CONTENT: 'rich_text_content',
  RATING: 'rating',
} as const;

export const SYSTEM_FIELDS = [
  'form_id',
  'form_token',
  'submission_id',
  'submitted_at',
  'link_expiry',
  'is_submitted',
  'created_at',
  'updated_at',
] as const;

export const FORM_STATES = {
  ACTIVE: 'Active',
  SUBMITTED: 'Submitted',
  EXPIRED: 'Expired',
  DELETED: 'Deleted',
} as const;
